[package]
name = "ciphersuite"
version = "0.4.99"
description = "Ciphersuites built around ff/group"
license = "MIT"
repository = "https://github.com/kayabaNerve/trout/tree/develop/ciphersuite"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["ciphersuite", "ff", "group"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
std-shims = { git = "https://github.com/serai-dex/serai", rev = "865e351f96bb90f05ad3f9966b631232192778ef", version = "0.1.4", default-features = false, optional = true }
zeroize = { version = "1", default-features = false }
ciphersuite_upstream = { package = "ciphersuite", git = "https://github.com/serai-dex/serai", rev = "865e351f96bb90f05ad3f9966b631232192778ef", version = "=0.4.2", default-features = false }

[features]
alloc = ["std-shims", "zeroize/alloc", "ciphersuite_upstream/alloc"]
std = [
  "alloc",
  "std-shims/std",
  "zeroize/std",
  "ciphersuite_upstream/std",
]
default = ["std"]
