[package]
name = "two-round-ecdsa"
version = "0.1.0"
edition = "2024"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
subtle = { version = "2", default-features = false, features = ["std"] }
zeroize = { version = "1", default-features = false, features = ["std", "derive"] }
rand = { version = "0.10", default-features = false, features = ["std"] }
rand_chacha = { version = "0.10", default-features = false, features = ["std"] }

crypto-bigint = { version = "0.7", default-features = false, features = ["zeroize", "subtle", "alloc"] }
crypto-primes = { version = "=0.7.0", default-features = false }
malachite = { version = "0.9", default-features = false, features = ["naturals_and_integers"] }
rug = { version = "1", default-features = false, features = ["std", "integer"], optional = true }

group = { version = "0.13", default-features = false, features = ["alloc"] }
multiexp = { version = "0.4", default-features = false, features = ["std"] }
ciphersuite = { version = "=0.4.2", git = "https://github.com/serai-dex/serai", rev = "d48325c69b787b37731a97d5707f48c9c3b962a3", default-features = false, features = ["std"] }
dkg = { git = "https://github.com/serai-dex/serai", rev = "d48325c69b787b37731a97d5707f48c9c3b962a3", default-features = false, features = ["std"] }

class-groups = { path = "../class-groups", default-features = false, features = ["std"] }

blake3 = { version = "1", default-features = false, features = ["std"] }

sha2 = { version = "0.11", default-features = false, features = ["alloc"], optional = true }
k256 = { version = "0.13", default-features = false, features = ["std", "arithmetic", "bits"], optional = true }

[dev-dependencies]
ecdsa = { version = "0.16", default-features = false, features = ["std", "verifying"] }
k256 = { version = "0.13", default-features = false, features = ["ecdsa"] }

[features]
secp256k1 = ["sha2", "k256"]
