[package]
name = "threshold-ecdsa"
version = "0.0.1-alpha"
description = "A two-round threshold signing protocol for ECDSA signatures"
license = "AGPL-3.0-only"
include = ["../AGPL-3.0"]
repository = "https://github.com/kayabaNerve/trout/tree/develop/two-round-ecdsa"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["cryptography", "threshold", "ecdsa"]
edition = "2024"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--all-features", "-Z", "unstable-options", "--document-private-items", "--document-hidden-items"]

[lints]
workspace = true

[dependencies]
zeroize = { version = "1", default-features = false, features = ["std", "derive"] }
rand = { version = "0.10", default-features = false, features = ["std"] }
rand_chacha = { version = "0.10", default-features = false, features = ["std"] }

crypto-bigint = { version = "0.7", default-features = false, features = ["zeroize", "alloc"] }
crypto-primes = { version = "=0.7.0", default-features = false }
malachite = { version = "0.9", default-features = false, features = ["naturals_and_integers"] }

ff = { version = "0.14", default-features = false, features = ["bits"] }
group = { version = "0.14", default-features = false, features = ["alloc"] }

class-groups = { version = "0.0.1-alpha", path = "../class-groups", default-features = false, features = ["std"] }

blake3 = { version = "1", default-features = false, features = ["std"] }

hybrid-array = { version = "0.4", default-features = false, optional = true }
sha2 = { version = "0.11", default-features = false, features = ["alloc"], optional = true }
k256 = { version = "0.14.0-rc.10", default-features = false, features = ["std", "arithmetic"], optional = true }

[dev-dependencies]
ecdsa = { version = "0.17.0-rc.17", default-features = false, features = ["std"] }
k256 = { version = "0.14.0-rc.10", default-features = false, features = ["ecdsa"] }

[features]
secp256k1 = ["hybrid-array", "sha2", "k256"]
