[package]
name = "two-round-ecdsa"
version = "0.1.0"
edition = "2024"

[dependencies]
subtle = { version = "2", default-features = false, features = ["std"] }
zeroize = { version = "1", default-features = false, features = ["std", "derive"] }
rand = { version = "0.10", default-features = false, features = ["std"] }
rand_chacha = { version = "0.10", default-features = false, features = ["std"] }

crypto-bigint = { version = "0.7", default-features = false, features = ["zeroize", "alloc"] }
crypto-primes = { version = "=0.7.0", default-features = false }
malachite = { version = "0.9", default-features = false, features = ["naturals_and_integers"] }
rug = { version = "1", default-features = false, features = ["std", "integer"], optional = true }

group = { version = "0.13", default-features = false, features = ["alloc"] }
multiexp = { version = "0.4", default-features = false, features = ["std"] }
dkg = { git = "https://github.com/serai-dex/serai", rev = "865e351f96bb90f05ad3f9966b631232192778ef", default-features = false, features = ["std"] }

class-groups = { path = "../class-groups" }

blake3 = { version = "1", default-features = false, features = ["std"] }

ciphersuite = { path = "../ciphersuite", default-features = false, features = ["std"], optional = true }
ciphersuite-kp256 = { git = "https://github.com/serai-dex/serai", rev = "865e351f96bb90f05ad3f9966b631232192778ef", version = "0.4", default-features = false, features = ["std"], optional = true }
generalized-bulletproofs = { git = "https://github.com/monero-oxide/monero-oxide", rev = "7216a2e84c7671c167c3d81eafe0d2b1f418f102", default-features = false, features = ["std"], optional = true }
generalized-bulletproofs-circuit-abstraction = { git = "https://github.com/monero-oxide/monero-oxide", rev = "7216a2e84c7671c167c3d81eafe0d2b1f418f102", default-features = false, features = ["std"], optional = true }

sha2 = { version = "0.11", default-features = false, features = ["alloc"], optional = true }
k256 = { version = "0.13", default-features = false, features = ["std", "arithmetic", "bits"], optional = true }
# ec-divisors defines an abstraction for getting a point's XY coordinates which we need for secq256k1 points
ec-divisors = { git = "https://github.com/monero-oxide/monero-oxide", rev = "7216a2e84c7671c167c3d81eafe0d2b1f418f102", default-features = false, features = ["std"], optional = true }
secq256k1 = { git = "https://github.com/serai-dex/serai", rev = "865e351f96bb90f05ad3f9966b631232192778ef", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
ecdsa = { version = "0.16", default-features = false, features = ["std", "verifying"] }
k256 = { version = "0.13", default-features = false, features = ["ecdsa"] }

[features]
gmp = ["rug", "class-groups/gmp"]
ddh-evrf = ["ciphersuite", "generalized-bulletproofs", "generalized-bulletproofs-circuit-abstraction"]
secp256k1 = ["sha2", "k256", "ciphersuite", "ciphersuite-kp256", "ec-divisors", "secq256k1", "ddh-evrf"]
default = ["ddh-evrf"]
