[package]
name = "trout-plus-plus"
version = "0.0.1-alpha"
description = "A two-round threshold signing protocol for ECDSA signatures"
license = "AGPL-3.0-only"
repository = "https://github.com/kayabaNerve/trout/tree/develop/trout-plus-plus"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
keywords = ["cryptography", "threshold", "ecdsa"]
edition = "2024"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "-Z", "unstable-options", "--document-private-items", "--document-hidden-items"]

[lints]
workspace = true

[dependencies]
zeroize = { version = "1", default-features = false, features = ["std", "derive"] }
rand = { version = "0.10", default-features = false, features = ["std"] }

cshake = { version = "0.2", default-features = false }
crypto-bigint = { version = "0.7", default-features = false, features = ["zeroize", "alloc"] }

ff = { version = "0.14", default-features = false, features = ["bits"] }
group = { version = "0.14", default-features = false, features = ["alloc"] }

class-groups = { version = "0.0.2-alpha", path = "../class-groups", default-features = false, features = ["alloc", "std"] }

sha2 = { version = "0.11", default-features = false, features = ["alloc"], optional = true }
p256 = { version = "0.14.0-rc.11", default-features = false, features = ["std", "arithmetic"], optional = true }
k256 = { version = "0.14.0-rc.11", default-features = false, features = ["std", "arithmetic"], optional = true }

[dev-dependencies]
sha2 = { version = "0.11", default-features = false, features = ["alloc"] }
ecdsa = { version = "0.17.0-rc.19", default-features = false, features = ["std"] }
p256 = { version = "0.14.0-rc.11", default-features = false, features = ["ecdsa"] }

crypto-bigint = { version = "0.7", default-features = false, features = ["zeroize", "extra-sizes", "alloc"] }

rand_core_06 = { package = "rand_core", version = "0.6", default-features = false, features = ["std"] }
ciphersuite = { version = "0.4.0", default-features = false }
ciphersuite-kp256 = { version = "0.4.0", default-features = false }
dkg-dealer = { version = "0.6.0", default-features = false }
bicycl = { version = "0.0.1-alpha", path = "../bicycl", default-features = false }

[features]
p256 = ["sha2", "dep:p256"]
secp256k1 = ["sha2", "k256"]
